In [1]:
!pip install pandas
!pip install numpy



In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("cosmetics.csv")

In [4]:
df

Label                          Brand  \
0     Moisturizer                         LA MER   
1     Moisturizer                          SK-II   
2     Moisturizer                 DRUNK ELEPHANT   
3     Moisturizer                         LA MER   
4     Moisturizer                   IT COSMETICS   
...           ...                            ...   
1467  Sun protect                         KORRES   
1468  Sun protect                KATE SOMERVILLE   
1469  Sun protect                  VITA LIBERATA   
1470  Sun protect  ST. TROPEZ TANNING ESSENTIALS   
1471  Sun protect                     DERMAFLASH   

                                                   Name  Price  Rank  \
0                                       Crème de la Mer    175   4.1   
1                              Facial Treatment Essence    179   4.1   
2                            Protini™ Polypeptide Cream     68   4.4   
3                           The Moisturizing Soft Cream    175   3.8   
4         Your Skin But Better™ CC+™ Cream with SPF 50+     38   4.1   
...                                                 ...    ...   ...   
1467  Yoghurt Nourishing Fluid Veil Face Sunscreen B...     35   3.9   
1468  Daily Deflector™ Waterlight Broad Spectrum SPF...     48   3.6   
1469                            Self Tan Dry Oil SPF 50     54   3.5   
1470                   Pro Light Self Tan Bronzing Mist     20   1.0   
1471  DERMAPROTECT Daily Defense Broad Spectrum SPF 50+     45   0.0   

                                            Ingredients  Combination  Dry  \
0     Algae (Seaweed) Extract, Mineral Oil, Petrolat...            1    1   
1     Galactomyces Ferment Filtrate (Pitera), Butyle...            1    1   
2     Water, Dicaprylyl Carbonate, Glycerin, Ceteary...            1    1   
3     Algae (Seaweed) Extract, Cyclopentasiloxane, P...            1    1   
4     Water, Snail Secretion Filtrate, Phenyl Trimet...            1    1   
...                                                 ...          ...  ...   
1467  Water, Alcohol Denat., Potassium Cetyl Phospha...            1    1   
1468  Water, Isododecane, Dimethicone, Butyloctyl Sa...            0    0   
1469  Water, Dihydroxyacetone, Glycerin, Sclerocarya...            0    0   
1470  Water, Dihydroxyacetone, Propylene Glycol, PPG...            0    0   
1471                      Visit the DERMAFLASH boutique            1    1   

      Normal  Oily  Sensitive  
0          1     1          1  
1          1     1          1  
2          1     1          0  
3          1     1          1  
4          1     1          1  
...      ...   ...        ...  
1467       1     1          1  
1468       0     0          0  
1469       0     0          0  
1470       0     0          0  
1471       1     1          1  

[1472 rows x 11 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1472 entries, 0 to 1471
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Label        1472 non-null   object 
 1   Brand        1472 non-null   object 
 2   Name         1472 non-null   object 
 3   Price        1472 non-null   int64  
 4   Rank         1472 non-null   float64
 5   Ingredients  1472 non-null   object 
 6   Combination  1472 non-null   int64  
 7   Dry          1472 non-null   int64  
 8   Normal       1472 non-null   int64  
 9   Oily         1472 non-null   int64  
 10  Sensitive    1472 non-null   int64  
dtypes: float64(1), int64(6), object(4)
memory usage: 126.6+ KB


In [6]:
!pip install scipy
!pip install -U scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import hstack, csr_matrix


In [7]:
df.columns

Index(['Label', 'Brand', 'Name', 'Price', 'Rank', 'Ingredients', 'Combination',
       'Dry', 'Normal', 'Oily', 'Sensitive'],
      dtype='object')

In [8]:
text_cols = ['Label', 'Brand', 'Name','Ingredients']
for cols in text_cols:
    df[cols] = df[cols].fillna("")

In [9]:
df['Price']= df['Price'].fillna(df['Price'].mean())
df['Rank'] = df['Rank'].fillna(df['Rank'].mean())


In [10]:
df['combined_text'] = df['Label'] + " " + df['Brand'] + " " + df['Name'] + " " + df['Ingredients']

In [11]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined_text'])

In [32]:
numeric_cols = ['Price', 'Rank','Combination',
       'Dry','Normal', 'Oily', 'Sensitive']
numeric_data = df[numeric_cols]

In [33]:
numeric_data

Price  Rank  Combination  Dry  Normal  Oily  Sensitive
0       175   4.1            1    1       1     1          1
1       179   4.1            1    1       1     1          1
2        68   4.4            1    1       1     1          0
3       175   3.8            1    1       1     1          1
4        38   4.1            1    1       1     1          1
...     ...   ...          ...  ...     ...   ...        ...
1467     35   3.9            1    1       1     1          1
1468     48   3.6            0    0       0     0          0
1469     54   3.5            0    0       0     0          0
1470     20   1.0            0    0       0     0          0
1471     45   0.0            1    1       1     1          1

[1472 rows x 7 columns]

In [34]:
scaler = MinMaxScaler()
numeric_matrix = scaler.fit_transform(numeric_data)

In [35]:
numeric_matrix 

array([[0.46866485, 0.82      , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.47956403, 0.82      , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.17711172, 0.88      , 1.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.13896458, 0.7       , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.04632153, 0.2       , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.11444142, 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ]], shape=(1472, 7))

In [36]:
numcsr_matrix = csr_matrix(numeric_matrix)

In [42]:
print(numcsr_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7401 stored elements and shape (1472, 7)>
  Coords	Values
  (0, 0)	0.46866485013623976
  (0, 1)	0.82
  (0, 2)	1.0
  (0, 3)	1.0
  (0, 4)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (1, 0)	0.47956403269754766
  (1, 1)	0.82
  (1, 2)	1.0
  (1, 3)	1.0
  (1, 4)	1.0
  (1, 5)	1.0
  (1, 6)	1.0
  (2, 0)	0.17711171662125338
  (2, 1)	0.8800000000000001
  (2, 2)	1.0
  (2, 3)	1.0
  (2, 4)	1.0
  (2, 5)	1.0
  (3, 0)	0.46866485013623976
  (3, 1)	0.76
  (3, 2)	1.0
  (3, 3)	1.0
  (3, 4)	1.0
  :	:
  (1464, 5)	1.0
  (1464, 6)	1.0
  (1465, 0)	0.08446866485013624
  (1465, 1)	0.82
  (1466, 0)	0.12261580381471389
  (1466, 1)	0.78
  (1467, 0)	0.08719346049046321
  (1467, 1)	0.78
  (1467, 2)	1.0
  (1467, 3)	1.0
  (1467, 4)	1.0
  (1467, 5)	1.0
  (1467, 6)	1.0
  (1468, 0)	0.12261580381471389
  (1468, 1)	0.7200000000000001
  (1469, 0)	0.13896457765667575
  (1469, 1)	0.7000000000000001
  (1470, 0)	0.04632152588555859
  (1470, 1)	0.2
  (1471, 0)	0.11444141689373297
  

In [38]:
final_features = hstack([tfidf_matrix, numcsr_matrix]).tocsr()


In [39]:
from sklearn.neighbors import NearestNeighbors

knn_model = NearestNeighbors(metric = 'cosine',algorithm = 'brute')
knn_model.fit(final_features)

NearestNeighbors(algorithm='brute', metric='cosine')

In [40]:
final_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 108045 stored elements and shape (1472, 5317)>

In [21]:
indices_name = pd.Series(df.index, index = df['Name']).drop_duplicates()
indices_label = pd.Series(df.index, index = df['Label']).drop_duplicates()
indices_ingredients = pd.Series(df.index, index = df['Ingredients']).drop_duplicates()
indices_brand = pd.Series(df.index, index = df['Brand']).drop_duplicates()

In [22]:
indices_name

Name
Crème de la Mer                                                                     0
Facial Treatment Essence                                                            1
Protini™ Polypeptide Cream                                                          2
The Moisturizing Soft Cream                                                         3
Your Skin But Better™ CC+™ Cream with SPF 50+                                       4
                                                                                 ... 
Yoghurt Nourishing Fluid Veil Face Sunscreen Broad Spectrum SPF 30               1467
Daily Deflector™ Waterlight Broad Spectrum SPF 50+ PA+++ Anti-Aging Sunscreen    1468
Self Tan Dry Oil SPF 50                                                          1469
Pro Light Self Tan Bronzing Mist                                                 1470
DERMAPROTECT Daily Defense Broad Spectrum SPF 50+                                1471
Length: 1472, dtype: int64

In [41]:
print(final_features)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 108045 stored elements and shape (1472, 5317)>
  Coords	Values
  (0, 3187)	0.05688653967084631
  (0, 2679)	0.21819997557265597
  (0, 3083)	0.2168424993799837
  (0, 1316)	0.10909998778632798
  (0, 277)	0.06918082880973367
  (0, 4378)	0.10842124968999185
  (0, 1858)	0.05821526377918533
  (0, 3151)	0.10204829363621278
  (0, 3415)	0.10959009155752002
  (0, 3675)	0.10589241945428057
  (0, 2149)	0.03163285752161448
  (0, 2565)	0.08628887319090851
  (0, 3135)	0.10909998778632798
  (0, 5219)	0.09136227339139426
  (0, 2713)	0.13864053472730706
  (0, 271)	0.0819089666673375
  (0, 1097)	0.05824325205058365
  (0, 483)	0.10416480100675911
  (0, 2812)	0.10255923733462499
  (0, 4416)	0.20511847466924998
  (0, 2489)	0.1966560177687968
  (0, 4415)	0.20409658727242555
  (0, 4386)	0.1705258749305765
  (0, 1810)	0.1808682859680481
  (0, 2116)	0.09073932928066193
  :	:
  (1470, 3946)	0.23354355714840713
  (1470, 5031)	0.24326835212470213
  (1470

In [24]:
def get_recommendation(value, based_on='product_name', n=5):
    # Map the input column to its index
    index_map = {
        'product_name': indices_name,
        'labels': indices_label,
        'ingredients': indices_ingredients,
        'brand': indices_brand
    }

    if based_on not in index_map:
        return f"Invalid 'based_on' value: {based_on}. Choose from 'product_name', 'labels', 'ingredients', 'brand'."
    
    if value not in index_map[based_on]:
        return f"No product found with {based_on} = '{value}'"

    idx = index_map[based_on][value]
    distances, indices_knn = knn_model.kneighbors(final_features[idx], n_neighbors=n+1)

    # Exclude the first result (itself)
    recommended_indices = indices_knn.flatten()[1:]

    return df[['Name', 'Brand', 'Label', 'Price', 'Rank', 'Ingredients']].iloc[recommended_indices].reset_index(drop=True)


In [25]:
get_recommendation("Your Skin But Better™ CC+™ Cream with SPF 50+", 'product_name', 2)


Name         Brand  \
0  Your Skin But Better™ CC+Illumination™ Cream w...  IT COSMETICS   
1  Anti-Aging Armour™ Super Smart Skin-Perfecting...  IT COSMETICS   

         Label  Price  Rank                                        Ingredients  
0  Moisturizer     38   3.9  Water, Snail Secretion Filtrate, Titanium Diox...  
1  Sun protect     38   4.1  Water, Cyclopentasiloxane, Butyloctyl Salicyla...

In [26]:
value = 'Crème de la Mer'
based_on='product_name'
n = 6
index_map = {
        'product_name': indices_name,
        'labels': indices_label,
        'ingredients': indices_ingredients,
        'brand': indices_brand}
idx = index_map[based_on][value]
distances, indices_knn = knn_model.kneighbors(final_features[idx], n_neighbors=n+1)

In [27]:
indices_knn

array([[  0,  20, 355,   3, 502, 162, 940]])

In [28]:
distances

array([[3.33066907e-16, 5.39480684e-03, 5.42987246e-02, 5.87136268e-02,
        6.31030460e-02, 6.39231249e-02, 6.51230943e-02]])

In [29]:
recommended_indices = indices_knn.flatten()[1:]
recommended_indices

array([ 20, 355,   3, 502, 162, 940])

In [30]:
# !pip install joblib
# import joblib
# joblib.dump(knn_model, 'artifacts/knn_model.pkl')
# joblib.dump(tfidf, 'artifacts/tfidf_combined.pkl')
# joblib.dump(scaler, 'artifacts/scaler.pkl')
# df.to_csv('artifacts/cosmetics_cleaned.csv', index=False)